collections:
  content:
    output: true
    permalink: /:path
  assets:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
  - scope:
      path: ""
      type: "content"
    values:
      layout: default

markdown: kramdown

relative_links:
  enabled:     true
  collections: false

exclude:
  - archief
  - vendor

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-relative-links

remote_theme: VNG-Realisatie/jekyll-theme-vng

github: VNG-Realisatie/gemma-verwerkingenlogging

theme: jekyll-theme-time-machine

project_name: gemma-verwerkingenlogging
